package proyectolabo;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class buscar extends javax.swing.JFrame {

    /**
     * Creates new form dueño
     */
    public buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtnombre.setEnabled(false);
        txtapellido.setEnabled(false);
        txtsexo.setEnabled(false);
        txtdui.setEnabled(false);
        txtmascota.setEnabled(false);
        txttipo.setEnabled(false);
        txtsex.setEnabled(false);
        txtraza.setEnabled(false);
        txttamaño.setEnabled(false);
        txtedad.setEnabled(false);
        txtpeso.setEnabled(false);
        txtid.setEnabled(false);
    }
    //modificar datos
    public void modificar(){
        
    }
    
//muestra los datos
    public void mostrar(String nombre, String apellido,String dui,String sexo){
     
        txtnombre.setText(nombre);
     txtapellido.setText(apellido);
     txtdui.setText(dui);
     txtsexo.setText(sexo);
    }
    public void mostraranimal(String nombre,String edad,String tamaño, String peso,String sexo,String tipoanimal,String Dui,String raza, String id){
      txtmascota.setText(nombre);
      txttipo.setText(tipoanimal);
      txtsex.setText(sexo);
      txtraza.setText(raza);
      txttamaño.setText(tamaño);
      txtedad.setText(edad);
      txtpeso.setText(peso);
      txtid.setText(id);
    }
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarrg = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdui = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtsexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmascota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtraza = new javax.swing.JTextField();
        btncacelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txttamaño = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtsex = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarrg.setEnabled(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 85, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APELLIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 85, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DUI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtdui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduiActionPerformed(evt);
            }
        });
        jPanel1.add(txtdui, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 85, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SEXO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del dueño");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avanzar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 60, 60));

        txtsexo.setText(" ");
        jPanel1.add(txtsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dueñonew.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        buscarrg.addTab("dueño", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Datos de la mascota");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel2.add(txtmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de animal:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Raza");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel2.add(txtraza, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        btncacelar.setText("Cancelar");
        btncacelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncacelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncacelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tamaño:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel2.add(txttamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Edad:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel2.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Peso:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        jPanel2.add(txtpeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sexo");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        txtsex.setText(" ");
        jPanel2.add(txtsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, -1));

        txttipo.setText(" ");
        jPanel2.add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, -1));

        jLabel11.setText("ID_Mascota");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtid.setText(" ");
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 110, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dueñonew.png"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buscarrg.addTab("mascota", jPanel2);

        getContentPane().add(buscarrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncacelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncacelarActionPerformed
       menuopciones me = new menuopciones ();
       me.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncacelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
buscarrg.setSelectedIndex(1);      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtduiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduiActionPerformed

    }//GEN-LAST:event_txtduiActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
         buscarrg.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    

    private void txttamañoKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
      
    }

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
       
    }

    private void txtpesoKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
       
    }

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
      
    }

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        /*char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!Character.isLetter(dato)) {
            evt.consume();
        }*/
    }

    private void txtmascotaKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        /*char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!Character.isLetter(dato)) {
            evt.consume();
        }*/
    }

    private void txtrazaKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
       /* char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!Character.isLetter(dato)) {
            evt.consume();
        }*/
    }

    private void txtduiKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    /*    int limite = 8;
        if (txtdui.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9]")) {
            evt.consume();
        }*/
    }

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        //if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        //    txtapellido.requestFocus();
        //}
    }

    private void txtapellidoKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        //if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        //8    txtdui.requestFocus();
      //  }
    }

    private void txtduiKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
      //  if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      //      cbxsexo.requestFocus();
       // }
    }

    private void txtmascotaKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
       // if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        //    cbxanimal.requestFocus();
       // }

    }

    private void txtrazaKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
       // if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        //    txttamaño.requestFocus();
       // }
    }

    private void txttamañoKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
       // if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       //     txtedad.requestFocus();
       // }
    }

    private void txtedadKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
      //  if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       //     txtpeso.requestFocus();
       // }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncacelar;
    private javax.swing.JTabbedPane buscarrg;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdui;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmascota;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtraza;
    private javax.swing.JTextField txtsex;
    private javax.swing.JTextField txtsexo;
    private javax.swing.JTextField txttamaño;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
