
package proyectolabo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class eliminacion extends javax.swing.JFrame {

    /**
     * Creates new form dueño
     */ 
    public eliminacion() {
        initComponents();
        this.setLocationRelativeTo(null);       
    }
    String id1="";
    String duii="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtdui = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setEnabled(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DUI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtdui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduiActionPerformed(evt);
            }
        });
        txtdui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtduiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtduiKeyTyped(evt);
            }
        });
        jPanel1.add(txtdui, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 85, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del dueño");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avanzar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 60, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dueñonew.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        eliminar.addTab("dueño", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mascotas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jButton4.setText("regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtnombre.setText(" ");
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dueñonew.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        eliminar.addTab("mascota", jPanel2);

        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nom,tipo,edad,tamaño,peso,sexo,Dui,raza,id;
     String mysql = "SELECT * FROM animal WHERE Dui="+txtdui.getText();
          conectar cc = new conectar();
         Connection cn = cc.getConnection();
          //String nombre, apellido,dui,sexo;
        
          
         
              
      try {
           Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(mysql);
            
          while(rs.next()){
        nom=rs.getString("nomascota");
       tipo=rs.getString("tipoanimal");
       edad=rs.getString("edad");
       tamaño=rs.getString("tamaño");
       peso=rs.getString("peso");
       sexo=rs.getString("sexo");
       Dui=rs.getString("Dui");
       raza=rs.getString("raza");
       id=rs.getString("idmascota");
       id1=id;
       duii=Dui;
       //JOptionPane.showMessageDialog(null,"");
      txtnombre.setText(nom);
      eliminar.setSelectedIndex(1); 
          
             }  
      } catch (SQLException ex) {
          Logger.getLogger(ProyectoLabo.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "error al ingresar los datos del animal");
      }
      
      //datos del dueño
      
      String sql = "SELECT * FROM dueño WHERE dui="+duii;
         // conectar cc = new conectar();
          //Connection cn = cc.getConnection();
          String nombre, apellido,dui,sexoo;
        
          
         
              
      try {
           Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
          while(rs.next()){
        nombre=rs.getString("nombre");
       apellido=rs.getString("apellido");
       dui=rs.getString("dui");
       sexoo=rs.getString("sexo");
       //JOptionPane.showMessageDialog(null,nombre+apellido+dui+sexo);
      
       
          
             }  
      } catch (SQLException ex) {
          Logger.getLogger(ProyectoLabo.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "ierror al ingresar los datos de la persona");
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtduiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduiActionPerformed
if(txtdui.equals("")){
    JOptionPane.showMessageDialog(null,"el campo no debe estar vacio");
}else{
    
}
    }//GEN-LAST:event_txtduiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
menuopciones me = new menuopciones();
me.show();
this.dispose(); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtduiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtduiKeyTyped
        // TODO add your handling code here:
        int limite = 9;
        if (txtdui.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9]")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtduiKeyTyped

    private void txtduiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtduiKeyPressed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtduiKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
eliminar.setSelectedIndex(0);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // borrar la mascota 
         String sql = "DELETE FROM animal WHERE idmascota="+id1;
          conectar cc = new conectar();
          Connection cn = cc.getConnection();
    try {
         PreparedStatement pst =  cn.prepareStatement(sql);
          pst.execute();
        JOptionPane.showMessageDialog(null, "se booro con exito el que nose");
      } catch (SQLException ex) {
          Logger.getLogger(ProyectoLabo.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "fallo al borrar");
      }
    String mysql = "DELETE FROM dueño WHERE dui="+duii;
         // conectar cc = new conectar();
          //Connection cn = cc.getConnection();
    try {
         PreparedStatement pst =  cn.prepareStatement(mysql);
          pst.execute();
        JOptionPane.showMessageDialog(null, "se borro con exito el dueño no pago :)");
      } catch (SQLException ex) {
          Logger.getLogger(ProyectoLabo.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "fallo al borrar");
      }
    
    }//GEN-LAST:event_jButton2ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtdui;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
